### ISSUE TITLE
Detect and filter out deprecated packages

### ISSUE THREAD

**Issue by kit-ty-kate** [ocurrent/opam-health-check#8]
We need some way of tagging packages as "deprecated" so that they don't show up when the "Only show the latest version of each packages" option is enabled.

Would a `deprecated` flag in the opam file work? e.g.
```
flags: [deprecated]
```

**Comment by avsm** [comment]
I think that's worth an upstream ocaml/opam issue, to help spec it out, as this is useful beyond health check. There have been requests for this for marking older packages that have been renamed (e.g. conduit-mirage <- mirage-conduit) or for ones the author doesn't want to support any more for their own reasons.

For these sorts of features, we could start with an x-field, but then move to deeper integration with the solver.  I'd imagine an initial version could have the 0install-solver mark any packages with an `x-deprecated` as conflicts to the solver so they are not selected in dependencies either. 

When we add fields to opam in a future revision, we could have a `deprecated` or `alerts` field to complement the current `available`.

**Comment by kit-ty-kate** [comment]
I think I'd rather have `deprecated` flag than a `x-deprecated` field. A `x-deprecated` field doesn't make much sense to me as I do not see what the value would be. `flags: deprecated` passes the opam lint test so there is no harm in adding it.

I'll open an issue for a solver integration though, for sure.
